- name: Update the Episode
  hosts: all
  gather_facts: false
  collections:
    - containers.podman
  vars:
    controller_host: localhost
    is_group: true
    new_status: 4
    controller_token: KeidQrFmVGYe0VBmAYopx8rMOSqMSD
    controller_host: localhost
    comment_text: |
        Investigated â€“ root cause fixed by Ansible Automation Platform job: 

  vars_files:
    - splunk
    
  tasks:

    - name: Episode ID
      debug:
        msg: "{{ episode_id }}"
        
    - name: Check if episode exists
      uri:
       url: "https://18.130.194.82:{{ splunk_port }}/servicesNS/nobody/SA-ITOA/event_management_interface/notable_event_group/{{ episode_id }}"
       method: GET
       user: "{{ splunk_user }}"
       password: "{{ splunk_pass }}"
       force_basic_auth: yes
       validate_certs: no

    - name: Add comment to Splunk notable event
      uri:
        url: https://{{ splunk_host }}:{{ splunk_port }}/servicesNS/nobody/SA-ITOA/event_management_interface/notable_event_comment
        method: POST
        user: "{{ splunk_user }}"
        password: "{{ splunk_pass }}"
        force_basic_auth: yes
        validate_certs: no
        headers:
          Content-Type: application/json
        body_format: json
        body:
          comment: "{{ comment_text }}"
          event_id: "{{ episode_id }}"
          is_group: true
        status_code: 200
      register: comment_response

    - name: Display comment response
      debug:
        var: comment_response.json

    - name: Set episode status to Resolved
      ansible.builtin.uri:
        url: "https://{{ splunk_host }}:{{ splunk_port }}/servicesNS/nobody/SA-ITOA/event_management_interface/notable_event_group/{{ episode_id }}"
        method: POST
        user: "{{ splunk_user }}"
        password: "{{ splunk_pass }}"
        force_basic_auth: yes
        body:
          status: 4
        body_format: json
        validate_certs: false
        status_code: 200

  
